#!/bin/sh

if [ $# -ne 1 ] ; then
  echo "needs one arg"
  exit 1
fi

script_dir="$(realpath $0 | xargs -I{} dirname '{}')"

if [ ! -d "$script_dir/src/$1" ] ; then
  echo "appimage named \"$1\" is not installed"
  exit 1
fi

rm -rf "$script_dir/src/$1"
rm "$script_dir/bin/$1"
